version: "3"
services:
  counter:
    image: adrianrc/counterservice
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://database:5432/myuser
      - DB_USERNAME=myuser
      - DB_PASSWORD=mysecret
    ports:
      - "4567:4567"
  database:
    image: adrianrc/counterdatabase
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecret

