version: "3"
services:
  counter:
    image: counterservice
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://database:5432/myuser
      - DB_USERNAME=myuser
      - DB_PASSWORD=mysecret
    ports:
      - "4567:4567"
  database:
    image: counterdatabase
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecret
